guest/urls.py
from django.urls import path
from . import views
app_name = 'guest'
urlpatterns = [
    path('teacher/', views.teacher_index, name='teacher_index'),
    path('teacher/create', views.teacher_create, name='teacher_create'),
    path('teacher/edit/<int:ids>', views.teacher_edit, name='teacher_edit'),
    path('teacher/del/<int:ids>', views.teacher_del, name='teacher_del'),
    path('teacher/import/', views.teacher_import, name='teacher_import'),

]

schoosite/urls.py
from django.contrib import admin
from django.urls import path, include
from setting import views as sv
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', sv.index, name="index"),
    path('setting/', include('setting.urls')),
    path('guest/', include('guest.urls'))
]

guest/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from utils import param
from django.core import validators
# Create your models here.
type_choice = (('ch', '教师'), ('admin', '管理员'), ('back', '后勤人员'))
gender_choice = ((1, '女'), (2, '男'))


class Teacher(models.Model):
    name = models.CharField(max_length=50, verbose_name='姓名')
    pinx = models.CharField(max_length=100)
    username = models.CharField(max_length=100, null=True, blank=True)
    secode = models.CharField(max_length=5, null=True, blank=True)
    subject = models.CharField(max_length=20, null=True, blank=True, choices=param.get_subject(), verbose_name='科目')
    type = models.CharField(max_length=50, choices=type_choice)
    gender = models.SmallIntegerField(choices=gender_choice)
    graduate = models.CharField(max_length=100)
    school = models.CharField(max_length=100, null=True, blank=True)
    note = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = '教师'
        constraints = [models.UniqueConstraint(fields=['name', 'subject'], name='unique_teacher')]


class TeacherImport(models.Model):
    file = models.FileField(upload_to='excel', validators=[validators.FileExtensionValidator(['xls', 'xlsx'], message='必须为excel文件，后缀名为xls,xlsx!')])


@receiver(pre_delete, sender=TeacherImport)
def teacher_import_delete(sender, instance, **kwargs):
    instance.file.delete(True)

guest/forms.py
from django import forms
from .models import Teacher, TeacherImport


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name', 'pinx', 'subject', 'type', 'gender', 'graduate']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control col-md-6'}),
            'pinx': forms.TextInput(attrs={'class': 'form-control'}),
            'subject': forms.Select(attrs={'class': 'form-control'}),
            'type': forms.Select(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'graduate': forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            'name': '姓名',
            'pinx': '拼写',
            'subject': '任教科目',
            'type': '类型',
            'gender': '性别',
            'graduate': '毕业学校'
        }
        help_texts = {
            'name': '请输入教师的真实姓名',
            'pinx': '输入教师姓名的全拼，正确输入有利于快速找到该老师',
            'subject': '该教师的任教科目，可以为空',
            'type': '该教师的类型',
            'gender': '请选择教师性别，如有其他选项请告知',
            'graduate': '请输入该教师的最高学历的毕业学校'
        }
        error_messages = {
            'gender': {'invalid': '格式不正确'}
        }


class TeacherImportForm(forms.ModelForm):
    class Meta:
        model = TeacherImport
        fields = '__all__'
        widgets = {
            'file': forms.FileInput(attrs={'class': 'form-control'})
        }
        labels = {
            'file': '选择文件'
        }

guest/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpRequest
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Teacher, TeacherImport
from .forms import TeacherForm, TeacherImportForm
import pandas as pd
# Create your views here.


def teacher_index(request):
    teachers = Teacher.objects.all().order_by('pinx')
    search = ""
    if request.GET.get('search'):
        search = request.GET.get('search')
        teachers = Teacher.objects.filter(pinx__contains=search)
        search = "&search="+search
    p = Paginator(teachers, 15, orphans=True)
    page = p.get_page(request.GET.get('page'))
    path = HttpRequest.get_full_path(self=request)
    return render(request, 'teacher/index.html', {'teachers': teachers, 'page': page, 'search': search, 'path': path})


def teacher_create(request):
    form = TeacherForm()
    if request.method == 'POST':
        form = TeacherForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '新增教师成功！')
            return redirect(reverse('guest:teacher_index'))
    return render(request, 'teacher/create.html', {'form': form})


def teacher_import(request):
    form = TeacherImportForm()
    if request.method == 'POST':
        form = TeacherImportForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save()
            print(f.file.path)
            book = pd.read_excel(f.file.path, sheet_name=0)
            book = book.fillna("")
            #all_data = book.head(5).T.to_dict()
            all_data = book.to_dict(orient='records')
            # t_list = list()
            # for s in all_data:
            #     print(s)
            #     t = Teacher(**s)
            #     t_list.append(t)
            t_list = [Teacher(**s) for s in all_data]
            Teacher.objects.bulk_create(t_list)
            #t = Teacher()
            #t.save()
            #print(book.head(5).T.to_dict())

            f.delete()

    return render(request, 'teacher/import.html', {'form': form})


def teacher_edit(request, ids):
    teacher = get_object_or_404(Teacher, pk=ids)
    form = TeacherForm(instance=teacher)
    if request.method == 'POST':
        form = TeacherForm(data=request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            messages.success(request, '教师'+teacher.name+'信息修改成功！')
            return redirect(reverse('guest:teacher_index'))
    return render(request, 'teacher/edit.html', {'form': form, 'teacher':teacher})


def teacher_del(request, ids):
    path = request.GET.get('path')
    teacher = get_object_or_404(Teacher, pk=ids)
    teacher.delete()
    messages.success(request, '教师<'+teacher.name+">删除成功！")
    if path:
        print(path)
        return redirect(path)
    else:
        return redirect(reverse('guest:teacher_index'))

guest/templates/teacher/create.html
{% extends 'layout.html' %}
{% block title %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>教师管理</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Simple Tables</li>
    </ol>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card  card-primary">
          <div class="card-header">
            <h3 class="card-title">新增教师数据</h3>
          </div>
          <!-- /.card-header -->
        <form method="post" action="{% url 'guest:teacher_create' %}">
          <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">提交数据</button>
          </div>
        </form>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <!-- /.row -->

    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

guest/templates/teacher/edit.html
{% extends 'layout.html' %}
{% block title %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>教师管理</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Simple Tables</li>
    </ol>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card  card-primary">
          <div class="card-header">
            <h3 class="card-title">新增教师数据</h3>
          </div>
          <!-- /.card-header -->
        <form method="post" action="{% url 'guest:teacher_edit' teacher.id %}">
          <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">提交数据</button>
          </div>
        </form>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <!-- /.row -->

    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

guest/templates/teacher/import.html
{% extends 'layout.html' %}
{% block title %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>教师管理</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Simple Tables</li>
    </ol>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card  card-primary">
          <div class="card-header">
            <h3 class="card-title">导入教师数据</h3>
          </div>
          <!-- /.card-header -->
        <form method="post" action="{% url 'guest:teacher_import' %}" enctype="multipart/form-data">
          <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">导入数据</button>
          </div>
        </form>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <!-- /.row -->

    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

guest/templates/teacher/index.html
{% extends 'layout.html' %}
<!-- 标题和导航位置 -->
{% block title %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>教师管理</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="/">主页</a></li>
      <li class="breadcrumb-item active">教师管理主页</li>
    </ol>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- 页面内容区域 -->
<section class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card card-info card-outline">
          <div class="card-header">
            <a class="btn btn-info" href="{% url 'guest:teacher_create' %}"><i class="fas fa-user-plus"></i>添加新教师</a>
            <a class="btn btn-info" href="{% url 'guest:teacher_import' %}"><i class="fas fa-upload"></i>批量导入</a>
            <div class="card-tools">
            <form method="get" action="{% url 'guest:teacher_index' %}">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="search" class="form-control float-right" placeholder="使用拼音搜索">
                <div class="input-group-append">
                  <button type="submit" class="btn btn-default">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            </form>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0">
              <table class="table table-hover text-nowrap">
                <thead>
                    <tr><th>id</th><th>姓名</th><th>拼写</th><th>用户名</th><th>安全码</th>
                        <th>任教科目</th><th>类型</th><th>性别</th><th>毕业学校</th><th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for teacher in page.object_list %}
                        <tr><td>{{ forloop.counter }}</td>
                            <td>{{ teacher.name }}</td>
                            <td>{{ teacher.pinx }}</td>
                            <td>{{ teacher.username }}</td>
                            <td>{{ teacher.secode }}</td>
                            <td>{{ teacher.get_subject_display }}</td>
                            <td>{{ teacher.get_type_display }}</td>
                            <td>{{ teacher.get_gender_display }}</td>
                            <td>{{ teacher.graduate }}</td>
                            <td><a  href="{% url 'guest:teacher_edit' teacher.id %}"><i class="fas fa-user-edit"></i> 编辑</a> |
                                <a class="text-danger" href="{% url 'guest:teacher_del' teacher.id %}?path={{ path }}"><i class="fas fa-user-minus"></i> 删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>

          </div>
          <!-- /.card-body -->
          <div class="card-footer">

            <ul class="pagination justify-content-end">
               <li class="page-item"><a class="page-link">共<span class="badge badge-info">{{ page.paginator.num_pages }}</span> 页,<span class="badge badge-info">{{ page.paginator.count }} </span>条数据</a></li>
                {% if page.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="{% url 'guest:teacher_index' as index %}?page={{ page.previous_page_number }}{{ search }}" tabindex="-1" aria-disabled="true"><i class="fas fa-backward"></i>上一页</a>
                </li>
                {% endif %}
                {% for i in page.paginator.page_range %}
                    {% if i == page.number %}
                        <li class="page-item active" aria-current="page">
                          <span class="page-link">
                            {{ page.number }}
                            <span class="sr-only">(current)</span>
                          </span>
                        </li>
                    {% elif i <= page.number|add:-4 or i >= page.number|add:4 %}

                    {% else %}
                        <li class="page-item"><a class="page-link" href="{{ index }}?page={{ i }}{{ search }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page.has_next %}
                <li class="page-item">
                  <a class="page-link" href="{{ index }}?page={{ page.next_page_number }}{{ search }}">下一页<i class="fas fa-forward"></i></a>
                </li>
                {% endif %}
            </ul>
          </div>
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
{% endblock %}