guest/urls.py
from django.urls import path
from . import views
app_name = 'guest'
urlpatterns = [
    path('teacher/', views.teacher_index, name='teacher_index'),
    path('teacher/create', views.teacher_create, name='teacher_create'),
    path('teacher/edit/<int:ids>', views.teacher_edit, name='teacher_edit'),
    path('teacher/del/<int:ids>', views.teacher_del, name='teacher_del'),
    path('teacher/import/', views.teacher_import, name='teacher_import'),

]

schoosite/urls.py
from django.contrib import admin
from django.urls import path, include
from setting import views as sv
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', sv.index, name="index"),
    path('setting/', include('setting.urls')),
    path('guest/', include('guest.urls'))
]

setting/urls.py
from django.urls import path
from . import views
app_name = 'setting'
urlpatterns = [
    path('department/', views.department_index, name='department-index'),
    path('department_create/', views.department_create, name='department-create'),
    path('department_edit/<int:ids>', views.department_edit, name='department-edit'),
    path('department_del/<int:ids>', views.department_del, name='department-del'),
    path('term/', views.term_index, name='term-index'),
    path('term/create/', views.term_create, name='term-create'),
    path('term/edit/<int:ids>', views.term_edit, name='term-edit'),
    path('term/del/<int:ids>', views.term_del, name='term-del')
]

setting/models.py
from django.db import models
from django.core import validators
from django import forms
# Create your models here.


class Department(models.Model):
    title = models.CharField(max_length=50)
    entry_year = models.CharField(max_length=4)
    person_in_charge = models.CharField(max_length=40)
    note = models.CharField(max_length=100, null=True, blank=True)


class Banji(models.Model):
    title = models.CharField(max_length=200)
    grade = models.CharField(max_length=4)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    serial = models.SmallIntegerField()
    type = models.CharField(max_length=10)
    school = models.CharField(max_length=100, null=True, blank=True)
    note = models.CharField(max_length=200, null=True, blank=True)


class Term(models.Model):
    title = models.CharField(max_length=200, verbose_name='学期标题')
    start = models.DateField(verbose_name='开始日期')
    end = models.DateField(verbose_name='结束日期')
    note = models.CharField(max_length=200, null=True, blank=True)

setting/forms.py
from django import forms
from setting.models import Department, Term, Banji

# class DepartmentForm(forms.Form):
#     title = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'special'}))
#     entry_year = forms.CharField(max_length=4)
#     person_in_charge = forms.CharField(max_length=40)
#     note = forms.CharField(max_length=100)


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['title', 'entry_year', 'person_in_charge', 'note']
        widgets = {
          'title': forms.TextInput(attrs={'class': 'form-control form-control-border'}),
          'entry_year': forms.TextInput(attrs={'class': 'form-control'}),
          'person_in_charge': forms.TextInput(attrs={'class': 'form-control'}),
          'note': forms.TextInput(attrs={'class': 'form-control'})
        }
        labels = {
            'title': "标题",
            'entry_year': "入学年份",
            'person_in_charge': '负责人',
            'note': '备注'

        }
        help_texts = {
            'title': '标题内容为教学部的名字',
            'entry_year': '请输入当前管理年级的入学年份，将决定可以管理到哪个年级的数据',
            'person_in_charge': '年级当前负责人，用于教师分辨自己所属年级',
            'note': '其他需要注明的信息'
        }

        # def __init__(self, *args, **kwargs):
        #     super(DepartmentForm, self).__init__(*args, **kwargs)
        #     for field in iter(self.fields):
        #         self.fields[field].widget.attrs.update({'class': 'form-control1'})


class TermForm(forms.ModelForm):
    #start = forms.DateTimeField(input_formats=['%Y-%m-%d H:m:s'],widget=forms.DateTimeInput(attrs={'class': 'form-control'}))
    #end = forms.DateTimeField(input_formats=['%Y-%m-%d H:m:s'],widget=forms.DateTimeInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Term
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'start': forms.DateInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'end': forms.DateInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'note': forms.TextInput(attrs={'class': 'form-control'}),
        }
        help_texts = {
            'title': '学期标题，请以 (xxxx年x季学期) 的格式或其他格式统一命名',
            'start': '学期开始的日期',
            'end': '学期结束的日期',
            'note': '其他备注信息',
        }

setting/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from .models import Department, Term, Banji
from .forms import DepartmentForm, TermForm
# Create your views here.


def index(request):
    return HttpResponse("这是预想中的设置中心")


def department_index(request):
    departments = Department.objects.all()
    return render(request, 'department/index.html', {'departments': departments})


def department_create(request):
    form = DepartmentForm()
    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, request.POST.get('title')+"内容已被添加，操作成功！")
            return redirect(reverse('setting:department-index'))
    return render(request, 'department/create.html', {'form': form})


def department_edit(request, ids):
    department = get_object_or_404(Department, pk=ids)
    if request.method == 'POST':
        form = DepartmentForm(data=request.POST, instance=department)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, department.title+"设置已被修改，操作成功！")
            return redirect(reverse('setting:department-index'))
    else:
        form = DepartmentForm(instance=department)
    return render(request, 'department/edit.html', {'form': form, 'department': department})


def department_del(request, ids):
    department = get_object_or_404(Department, pk=ids)
    department.delete()
    return redirect(reverse('setting:department-index'))


def term_index(request):
    terms = Term.objects.all()
    return render(request, 'term/index.html', {'terms': terms})


def term_create(request):
    form = TermForm()
    if request.method == 'POST':
        form = TermForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '新增学期成功！')
            return redirect(reverse('setting:term-index'))
    return render(request, 'term/create.html', {'form': form})


def term_edit(request, ids):
    term = get_object_or_404(Term, pk=ids)
    form = TermForm(instance=term)
    if request.method == 'POST':
        form = TermForm(data=request.POST, instance=term)
        if form.is_valid():
            form.save()
            messages.success(request, term.title+'-数据修改成功!')
            return redirect(reverse('setting:term-index'))
    return render(request, 'term/edit.html', {'form': form, 'term': term})


def term_del(request, ids):
    term = get_object_or_404(Term, pk=ids).delete()
    messages.success(request, term.title+' 已被成功删除！')
    return redirect(reverse('setting:term-index'))

setting/templates/department/create.html
{% extends 'layout.html' %}

{% block title %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>教学部管理</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Simple Tables</li>
    </ol>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card  card-info">
          <div class="card-header">
            <h3 class="card-title">新增教学部数据</h3>
          </div>
          <!-- /.card-header -->
        <form method="post" action="{% url 'setting:department-create' %}" class="form-horizontal">
          <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">提交</button>
          </div>
        </form>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <!-- /.row -->

    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

setting/templates/department/edit.html
{% extends 'layout.html' %}
{% block title %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>教学部管理</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Simple Tables</li>
    </ol>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card  card-primary">
          <div class="card-header">
            <h3 class="card-title">新增教学部数据</h3>
          </div>
          <!-- /.card-header -->
        <form method="post" action="{% url 'setting:department-edit' department.id %}">
          <div class="card-body">
              {% csrf_token %}
              {{ form.as_p }}
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">提交</button>
          </div>
        </form>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <!-- /.row -->

    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

setting/templates/department/index.html
{% extends 'layout.html' %}
<!-- 标题和导航位置 -->
{% block title %}
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>教学部管理</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Simple Tables</li>
    </ol>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- 页面内容区域 -->
<section class="content">
  <div class="container-fluid">
    <!-- /.row -->
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <a class="btn btn-info" href="{% url 'setting:department-create' %}">添加数据</a>
              <a class="btn btn-danger" href="{% url 'setting:department-create' %}">清空数据</a>
            <div class="card-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                <div class="input-group-append">
                  <button type="submit" class="btn btn-default">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0">
              <table class="table table-hover text-nowrap">
                <thead>
                    <tr><th>id</th><th>标题</th><th>入学年份</th><th>负责人</th><th>备注</th><th>操作</th></tr>
                </thead>
                <tbody>
                    {% for department in departments %}
                        <tr><td>{{ department.id }}</td>
                            <td>{{ department.title }}</td>
                            <td>{{ department.entry_year }}</td>
                            <td>{{ department.person_in_charge }}</td>
                            <td>{{ department.note }}</td>
                            <td><a href="{% url 'setting:department-edit' department.id %}"><i class="fas fa-user-edit"></i> 编辑</a> |
                                <a href="{% url 'setting:department-del' department.id %}"><i class="fas fa-user-minus"></i> 删除</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>

          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
{% endblock %}